blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('chat/', include('chat.urls', namespace='chat')),
                  path('user/', include('accounts.urls', namespace='accounts')),
                  path('like/', include('like.urls')),
                  path('', include('post.urls', namespace='post')),
                  path('', include('django.contrib.flatpages.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path

from chat.views import RoomListView, RoomDetailView

app_name = 'Чат'

urlpatterns = [
    path(r'list/', RoomListView.as_view(), name='room-list'),
    path(r'detail/<int:pk>/', RoomDetailView.as_view(), name='room-detail'),
]

chat/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Room(models.Model):
    name = models.CharField(_('Room name'), max_length=255)
    created_datetime = models.DateTimeField(_('Created datetime'), auto_now_add=True)
    updated_datetime = models.DateTimeField(_('Updated datetime'), auto_now=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = _('Комната')
        verbose_name_plural = _('Комнаты')


class Message(models.Model):
    created_datetime = models.DateTimeField(_('Created datetime'), auto_now_add=True)
    updated_datetime = models.DateTimeField(_('Updated datetime'), auto_now=True)
    message = models.TextField(_('Message'), max_length=1000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey('chat.Room', on_delete=models.CASCADE)

    def __str__(self):
        return "{0} {1}".format(self.author, self.room)

    class Meta:
        verbose_name = _('Сообщение')
        verbose_name_plural = _('Сообщения')

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from .models import Room


class RoomListView(LoginRequiredMixin, ListView):
    model = Room
    template_name = 'chat/chat_list.html'


class RoomDetailView(LoginRequiredMixin, DetailView):
    model = Room
    template_name = 'chat/detail.html'

templates/chat/chat_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <h1>{% trans 'Выберите комнату:' %}</h1>
    {% for object in object_list %}
        <div class="col-lg-8">
            <a href="{% url 'chat:room-detail' object.pk %}">
                <h1 class="mt-4">{{ object.name }}</h1>
            </a>
        </div>
    {% empty %}
        <h1>{% trans 'Нету комнат' %}</h1>
    {% endfor %}
{% endblock %}

templates/chat/detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block main %}
    <div class="col-lg-8">
        {% for msg in object.message_set.all %}
            {% include 'chat/includes/chat_message.html' %}
        {% empty %}
            <h6 id="text">{% trans 'Сообщений нету, напиши свое первое сообщение' %}</h6>
        {% endfor %}
        <hr>
    </div>
    <div class="col-lg-8">
        <textarea class="form-control" id="message" style="width: 100%; height: 200px;"></textarea>
        <button data-action="send_message">{% trans 'Отправить' %}</button>
    </div>
{% endblock %}


{% block extra_js %}
    <script>
      $( document ).ready( function() {
        const ws_scheme = window.location.protocol === 'https:' ? 'wss://' : 'ws://';
        const webSocket = new WebSocket( ws_scheme + window.location.host + "/{{ object.pk }}/" );
        webSocket.onmessage = function( e ) {
          var data = JSON.parse( e.data );
          if ($( '[data-action="chat_message"]').length > 0)
            $( '[data-action="chat_message"]:last' ).after( data[ 'message_html' ] );
          else
            $( '#text' ).replaceWith( data[ 'message_html' ] );
        };
        $( '[data-action="send_message"]' ).on( 'click', function() {
          $( this ).attr( 'disabled', true );
          const textarea = $( this ).closest( 'div' ).find( '#message' );
          const message = textarea.val();
          if ( message.length > 0 ) {
            webSocket.send(
              JSON.stringify( {
                'message': message,
                'author_id': {{ user.id }}
              } )
            );
          }
          textarea.val( '' );
          $( this ).attr( 'disabled', false );
        } );
      } );
    </script>
{% endblock %}