accounts/urls.py
from django.urls import path

from accounts.views import CustomLoginView, CustomLogoutView, RegisterCreateView, UserUpdateView
app_name = 'accounts'

urlpatterns = [
    path(r'login/', CustomLoginView.as_view(), name='login'),
    path(r'logout/', CustomLogoutView.as_view(), name='logout'),
    path(r'registration/', RegisterCreateView.as_view(), name='registration'),
    path(r'update/<int:pk>/', UserUpdateView.as_view(), name='update'),
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('chat/', include('chat.urls', namespace='chat')),
                  path('user/', include('accounts.urls', namespace='accounts')),
                  path('like/', include('like.urls')),
                  path('', include('post.urls', namespace='post')),
                  path('', include('django.contrib.flatpages.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path

from chat.views import RoomListView, RoomDetailView

app_name = 'Чат'

urlpatterns = [
    path(r'list/', RoomListView.as_view(), name='room-list'),
    path(r'detail/<int:pk>/', RoomDetailView.as_view(), name='room-detail'),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(r'', views.PostListView.as_view(), name='index'),
    path(r'edit/comment/<int:pk>/', views.CommentUpdateView.as_view(), name='comment-edit'),
    path(r'detail/comment/<int:pk>/', views.CommentDetailView.as_view(), name='comment-detail'),
    path(r'create_comment/<int:post_id>/', views.CommentCreateView.as_view(), name='create-comment'),
    path(r'detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path(r'edit/post/<int:pk>/', views.PostUpdateView.as_view(), name='edit'),
    path(r'delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path(r'create/', views.PostCreateView.as_view(), name='create'),
]

templates/base.html
{% load static %}
{% load i18n %}
{% load flatpages %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% trans 'MainAcademy Blog - ' %}
        {% block title %}Start Bootstrap Template{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'post:index' %}">{% trans 'My blog' %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post:create' %}">
                            {% trans 'Создать объявление' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chat:room-list' %}">
                            {% trans 'Чат комнаты' %}
                        </a>
                    </li>
                {% endif %}
                {% get_flatpages as flatpages %}
                {% for page in flatpages %}
                    <li class="nav-item">

                        <a class="nav-link" href="{{ page.url }}">
                            {{ page.title }}
                        </a>
                    </li>
                {% endfor %}
                {% if user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:login' %}">{% trans 'Войти' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:registration' %}">{% trans 'Регистрация' %}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:logout' %}">{% trans 'Выйти' %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if messages %}
    <div class="container">
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
            {% block main %}
                <!-- Title -->
                <h1 class="mt-4">Post Title</h1>

                <!-- Author -->
                <p class="lead">
                    by
                    <a href="#">Start Bootstrap</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p>Posted on January 1, 2018 at 12:00 PM</p>

                <hr>

                <!-- Preview Image -->
                <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

                <hr>

                <!-- Post Content -->
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus,
                    vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi
                    nam
                    quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus
                    doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab
                    tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus,
                    dolorem
                    iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic
                    porro optio ratione repellat perspiciatis. Enim, iure!</p>

                <blockquote class="blockquote">
                    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Integer
                        posuere erat a ante.</p>
                    <footer class="blockquote-footer">Someone famous in
                        <cite title="Source Title">Source Title</cite>
                    </footer>
                </blockquote>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum,
                    aliquid,
                    animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta
                    saepe minima ab quo voluptatem obcaecati?</p>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis.
                    Sunt,
                    ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate
                    voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

                <hr>

                <!-- Comments Form -->
                <div class="card my-4">
                    <h5 class="card-header">Leave a Comment:</h5>
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <textarea class="form-control" rows="3"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>

                <!-- Single Comment -->
                <div class="media mb-4">
                    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                    <div class="media-body">
                        <h5 class="mt-0">Commenter Name</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                        ante
                        sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra
                        turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia
                        congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment with nested comments -->
                <div class="media mb-4">
                    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                    <div class="media-body">
                        <h5 class="mt-0">Commenter Name</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                        ante
                        sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra
                        turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia
                        congue felis in faucibus.

                        <div class="media mt-4">
                            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50"
                                 alt="">
                            <div class="media-body">
                                <h5 class="mt-0">Commenter Name</h5>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                                scelerisque ante sollicitudin. Cras purus odio, vestibulum in
                                vulputate
                                at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
                                fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>

                        <div class="media mt-4">
                            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50"
                                 alt="">
                            <div class="media-body">
                                <h5 class="mt-0">Commenter Name</h5>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                                scelerisque ante sollicitudin. Cras purus odio, vestibulum in
                                vulputate
                                at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
                                fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            {% if user.is_authiticated %}
                <div class="card my-4">
                    {% with fullname=user.get_full_name %}
                        <h6 class="card-header">
                            {% blocktrans %}
                                Добро пожаловать, господин {{ fullname }}!
                            {% endblocktrans %}
                        </h6>
                    {% endwith %}
                    <div class="card-body">
                        {% if user.avatar %}
                            <img src="{{ user.avatar.url }}" style="width: 200px">
                        {% endif %}
                        <hr>
                        <a href="{% url 'accounts:update' user.id %}">
                            <h6>{% trans 'Редактировать профайл' %}</h6></a>

                    </div>
                </div>
            {% endif %}
            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">{% trans 'Search' %}</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="form-control"
                               placeholder="{% trans 'Search for...' %}">
                        <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">{% trans 'Go!' %}</button>
                </span>
                    </div>
                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">{% trans 'Tags' %}</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">{% trans 'Web Design' %}</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">{% trans 'JavaScript' %}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Side Widget -->
            {#            <div class="card my-4">#}
            {#                <h5 class="card-header">Side Widget</h5>#}
            {#                <div class="card-body">#}
            {#                    You can put anything you want inside of these side widgets. They are easy to#}
            {#                    use, and feature the new Bootstrap 4 card containers!#}
            {#                </div>#}
            {#            </div>#}

        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">{% trans 'Copyright' %}
            &copy; {% trans 'Copyright' %} {% now 'Y' %}</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% block extra_js %}
{% endblock %}
</body>

</html>