blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('chat/', include('chat.urls', namespace='chat')),
                  path('user/', include('accounts.urls', namespace='accounts')),
                  path('like/', include('like.urls')),
                  path('', include('post.urls', namespace='post')),
                  path('', include('django.contrib.flatpages.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

like/urls.py
from django.urls import path

from .views import *
app_name = 'like'

urlpatterns = [
    path(r'create/<int:type>/<int:id>/', LikeCreateView.as_view(), name='like'),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(r'', views.PostListView.as_view(), name='index'),
    path(r'edit/comment/<int:pk>/', views.CommentUpdateView.as_view(), name='comment-edit'),
    path(r'detail/comment/<int:pk>/', views.CommentDetailView.as_view(), name='comment-detail'),
    path(r'create_comment/<int:post_id>/', views.CommentCreateView.as_view(), name='create-comment'),
    path(r'detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path(r'edit/post/<int:pk>/', views.PostUpdateView.as_view(), name='edit'),
    path(r'delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path(r'create/', views.PostCreateView.as_view(), name='create'),
]

post/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils.translation import ugettext_lazy as _


class DatesAbstractModel(models.Model):
    created_datetime = models.DateTimeField(_('Время создание'), auto_now_add=True)
    updated_datetime = models.DateTimeField(_('Время последнего изменения'), auto_now=True)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name=_('Автор'))

    class Meta:
        abstract = True


class Post(DatesAbstractModel):
    title = models.CharField(_('Заголовок'), max_length=255)
    text = models.TextField(_('Текст новости'))
    likes = GenericRelation('like.Like', related_name='post_likes')

    def __str__(self):
        return " ".join([str(self.created_datetime), self.title])

    class Meta:
        ordering = ('-created_datetime',)
        verbose_name = _('Новость')
        verbose_name_plural = _('Новости')


class Comment(DatesAbstractModel):
    text = models.TextField(_('Комментарии'))
    post = models.ForeignKey('post.Post', on_delete=models.CASCADE, verbose_name=_('Новость'))
    likes = GenericRelation('like.Like', related_name='comment_likes')

    def __str__(self):
        return "Комментарий к новости - {0}".format(self.id)

    class Meta:
        ordering = ('created_datetime',)
        verbose_name = _('Комментарий')
        verbose_name_plural = _('Комментарии')

post/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Post, Comment


class CreatePostForm(forms.ModelForm):
    # title = forms.CharField(widget=forms.Textarea(attrs={'class': 'success'}))
    # text = forms.CharField(widget=forms.TextInput(attrs={'class': 'text'}))

    # def clean_text(self):
    #     raise forms.ValidationError('error in text')
    # def clean_title(self):
    #     raise forms.ValidationError('error in title')
    #
    # def clean(self):
    #     cleaned_data = super(CreatePostForm, self).clean()
    #     if cleaned_data.get('text'):
    #         self.add_error('text', 'error')
    #     if cleaned_data.get('title'):
    #         self.add_error('title', 'error title')
    #     return cleaned_data

    class Meta:
        model = Post
        fields = ['title', 'text']
        widgets = {
            'title': forms.TextInput(),
            'text': forms.Textarea(),
        }


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'placeholder': _('Введите ваш комментарий')})
    )

    class Meta:
        model = Comment
        fields = ['text']

post/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView
from django_filters.views import FilterView

from post.filters import PostFilters
from .forms import CreatePostForm, CommentForm
from .mixins import UserPostMixin
from .models import Post, Comment


def index(request):
    context = {'object_list': Post.objects.all()}
    return render(request, 'post/list.html', context)


def detail(request, *args, **kwargs):
    """
    отобразить все объекты из модели objects.all()
    найти только один объект из бд objects.get(param=data)
    найти все объекты  из бд подходящие по параметрам objects.filter(param=data)
    """
    context = {'object': get_object_or_404(Post, id=kwargs.get('pk'))}
    return render(request, 'post/detail.html', context)


def delete(request, *args, **kwargs):
    """
    GET/POST
    """
    if request.method == 'POST':
        post = get_object_or_404(Post, id=kwargs.get('pk'))
        post.delete()
        return HttpResponseRedirect('/')
    else:
        return render(request, 'post/delete_confirmation.html', {})


def create(request, *args, **kwargs):
    form = CreatePostForm
    if request.method == 'GET':
        return render(request, 'post/form.html', {'form': form})
    else:
        new_form = form(data=request.POST)
        if new_form.is_valid():
            new_form.save()
            return HttpResponseRedirect('/')
        else:
            return render(request, 'post/form.html',
                          {'form': form, 'btn_text': _('Создать объявление')})


def edit(request, *args, **kwargs):
    post = get_object_or_404(Post, pk=kwargs.get('pk'))
    if request.method == 'GET':
        return render(request, 'post/form.html', {'form': CreatePostForm(instance=post),
                                                  'btn_text': _('Редактировать объявление')})
    else:
        form = CreatePostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('post:detail', kwargs={'pk': post.pk}))
        else:
            return render(request, 'post/form.html',
                          {'form': form, 'btn_text': _('Редактировать объявление')})


class PostListView(FilterView):
    queryset = Post.objects.all().annotate(likes_count=Count('likes'))
    template_name = 'post/list.html'
    paginate_by = 2
    filterset_class = PostFilters


class PostDetailView(DetailView):
    template_name = 'post/detail.html'
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context.update({'form': CommentForm})
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = CreatePostForm
    template_name = 'post/form.html'
    queryset = Post.objects.all()

    def form_valid(self, form):
        new_form = form.save(commit=False)
        new_form.author = self.request.user
        new_form.save()
        return HttpResponseRedirect('/')


class PostDeleteView(UserPostMixin, DeleteView):
    template_name = 'post/delete_confirmation.html'
    success_url = '/'


class PostUpdateView(UserPostMixin, UpdateView):
    success_url = '/'
    form_class = CreatePostForm
    template_name = 'post/form.html'

    def get_context_data(self, **kwargs):
        context = super(PostUpdateView, self).get_context_data(**kwargs)
        context.update({'btn_text': _('Редактировать объявление')})
        return context

    def get_success_url(self):
        return reverse_lazy('post:detail', kwargs={'pk': self.object.pk})


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/detail.html'
    success_url = '/'

    def form_valid(self, form):
        data_form = form.save(commit=False)
        data_form.author = self.request.user
        data_form.post_id = self.kwargs['post_id']
        data_form.save()
        return JsonResponse({
            'status': 'ok',
            'comment': render_to_string('post/includes/comment.html',
                                        context={'comment': data_form})
        })

    def form_invalid(self, form):
        return JsonResponse({'status': 'fail', 'form': str(form)})


class CommentDetailView(LoginRequiredMixin, UpdateView):
    model = Comment
    template_name = 'post/includes/comment.html'
    context_object_name = 'comment'
    fields = '__all__'


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/comment_form.html'
    success_url = '/'

    def form_valid(self, form):
        super(CommentUpdateView, self).form_valid(form)
        return JsonResponse({
            'status': 'ok',
            'text': render_to_string(
                'post/includes/comment.html',
                context={'comment': self.object, 'user': self.request.user}
            )
        })

    def form_invalid(self, form):
        super(CommentUpdateView, self).form_invalid(form)
        return JsonResponse({
            'status': 'error',
            'form': render_to_string(
                self.template_name,
                context=self.get_context_data(),
                request=self.request
            )
        })

templates/post/comment_form.html
{% load i18n %}

<div class="col-lg-12" data-list="comment" style="border:1px solid black;">
    <br>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button
          type="button"
          data-url="{% url 'post:comment-edit' object.pk %}"
          class="btn btn-success"
          data-id="save_comment"
        >
          {% trans 'Сохранить' %}
        </button>
        <button
          type="button"
          data-url="{% url 'post:comment-detail' object.pk %}"
          data-id="close_edit"
          class="btn btn-danger"
        >
          {% trans 'Отменить' %}
        </button>
    </form>
    <br>
</div>

templates/post/delete_confirmation.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {% trans 'Вы уверены что хотите удалить новость?' %}
        <br>
        <button type="submit">{% trans 'Да' %}</button>
        <a href="{% url 'post:index' %}">
            <button type="button">{% trans ' Нет' %}</button>
        </a>
    </form>
{% endblock %}

templates/post/detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block main %}
    <div class="col-lg-8">

        <!-- Title -->
        <a href="{% url 'post:detail' object.id %}"><h1 class="mt-4">{{ object.title }}</h1></a>

        <!-- Author -->
        <p class="lead">
            {% trans 'Написан пользователем:' %}
            <a href="#">{{ object.author.get_full_name }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{% trans 'Опубликован в' %} {{ object.created_datetime }}</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">{{ object.text }}</p><br>
        {% if user == object.author %}
            <a href="{% url 'post:edit' object.id %}">{% trans 'Изменить' %}</a>
        {% endif %}
        {% if user.is_authenticated %}
            <button
                    type="button"
                    data-action="like"
                    data-url="{% url 'like:like' object.likes.content_type.id object.id %}"
            >
                &hearts;<span id="counter">{% if object.likes.count > 0 %}
                {{ object.likes.count }}{% endif %}</span>
            </button>
            <hr>
            <form action="{% url 'post:create-comment' object.id %}" method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <button type="button" data-action="create_comment">
                    {% trans 'Отправить комментарий' %}
                </button>
            </form>
            <br>
        {% endif %}
        {% for comment in object.comment_set.all %}
            {% include 'post/includes/comment.html' %}
        {% endfor %}


    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/post_detail.js' %}"></script>
    <script>
      $('body').on( 'click', '[data-action="edit_comment"]', function() {
        const url = $( this ).data( 'url' );
        let self = $( this );
        $.get( url, function( e ) {
          self.closest('[data-list="comment"]').replaceWith(e)
        } );
      } );
      $('body').on( 'click', '[data-id="close_edit"]', function() {
        const url = $( this ).data( 'url' );
        let self = $( this );
        $.get( url, function( e ) {
          self.closest('[data-list="comment"]').replaceWith(e)
        } );
      } );
      $('body').on('click', '[data-id="save_comment"]', function () {
        const self = $(this),
                form = self.closest('form');
        let data = {
          'text': form.find('textarea[name="text"]').val(),
          'csrfmiddlewaretoken': form.find('input[name="csrfmiddlewaretoken"]').val()
        };
        $.post(self.data('url'), data, function( e ) {
          if (e.status === 'ok'){
            self.closest('[data-list="comment"]').replaceWith(e.text)
          } else {
            form.replaceWith(e.form)
          }
        })
      })
    </script>
{% endblock %}

templates/post/form.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    {% trans 'Страница создания объявления' %}
    <form method="post">
        {% csrf_token %}
        <label id="{{ form.title.id_for_label }}">{% trans 'Заголовок' %}</label><br>
        {{ form.title }}<br>
        <span class="alert">{{ form.errors.title }}</span><br>
        <label id="{{ form.text.id_for_label }}">{% trans 'Текст' %}</label><br>
        {{ form.text }}<br>
        {{ form.errors.text }}<br>
        <button type="submit">
            {% if btn_text %}
                {{ btn_text }}
            {% else %}
                {% trans 'Кнопка' %}
            {% endif %}
        </button>
    </form>
{% endblock %}

templates/post/list.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <form>
      {{ filter.form.as_p }}
        <button>{% trans 'Применить' %}</button>
    </form><br>
    {% for obj in filter.qs %}
        {% with obj as object %}
            {% include 'post/includes/short_post.html' %}
        {% endwith %}
    {% empty %}
        <h1>{% trans 'Нету записей' %}</h1>
    {% endfor %}
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>

{% endblock %}